# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: gmail.com
  secret_key_base: a9452e88b8e4897ff799ae12f5f3f99f70c55b73198eb1f257212a12dbeb8d472728ab8856293017cbcff8ac7e511e500a65b3d12a44388661e91f369c2b1608

test:
  domain_name: example.com 
  secret_key_base: 2d16a447ceccae159a054d7b1da598c5eed2a390fbb26217299820283ff0d61596f1f280070013be85fbc73842656dcc89f9e780204dd485a24271a2dbab7e06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
